// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smjabbpukcmeorldjerm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtamFiYnB1a2NtZW9ybGRqZXJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3OTMwMDUsImV4cCI6MjA2NDM2OTAwNX0.3YmY91ie2YAkbtPZiO_AiTc5eKIJeFb3zwMOI8thrlA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);